### ISSUE TITLE
Not clear how to use estimates

### ISSUE THREAD

**Issue by altaurog** [mw44118/pitz#4]
My intuition tells me that when I create a task, I should be able to enter my estimate for that task directly.  However, I am apparently expected to _choose_ an estimate from a pre-existing list of estimates.

```
webapp 14:42 1052 $ pitz-add-task -t "Data Feed"
Choose a Milestone
   1: 05227a unscheduled: 0% complete (0 / 0 tasks)
   2: d982fe Iteration_4: 0% complete (0 / 0 tasks)
   3: 50e2d7 Iteration_3: 0% complete (0 / 0 tasks)
   4: bb2010 Iteration_2: 0% complete (0 / 0 tasks)
   5: 1b2472 Iteration_1: 0% complete (0 / 0 tasks)
Pick a Milestone or hit <ENTER> to choose 05227a unscheduled: 0% complete (0 / 0 tasks): 1
Choose a Estimate
   1: 48c188: not estimated
Pick a Estimate or hit <ENTER> to choose 48c188: not estimated: 7
Traceback (most recent call last):
  File "/usr/bin/pitz-add-task", line 9, in <module>
    load_entry_point('pitz==1.1.2', 'console_scripts', 'pitz-add-task')()
  File "/usr/lib/python2.5/site-packages/pitz/cmdline/__init__.py", line 301, in __call__
    self.handle_proj(p, options, args, proj)
  File "/usr/lib/python2.5/site-packages/pitz/cmdline/__init__.py", line 1179, in handle_proj
    else Estimate.choose_from_already_instantiated(default_estimate),
  File "/usr/lib/python2.5/site-packages/pitz/entity/__init__.py", line 545, in choose
    return choices[int(choice)-1]
IndexError: list index out of range
```

I don't quite understand the logic here.  In my mind, estimates are just real numbers and have no meaning outside the context of an existing task.  What am I missing?

**Comment by mw44118** [comment]
Hi Alturog -- thanks for the question.

I'm curious.  How do you estimate tasks?  Do you use a number that can be any value between one and a billion, or do you choose from a list?

If you just want to assign arbitrary values without pre-defining choices ahead of time, you can do that, but use a different key name.  This will work just fine:

$ pitz-edit abc123 altaurog-estimate

Then when your $EDITOR opens, you can store whatever text you want in there.

In my case, I want the estimate slot to point to a particular estimate object, that I defined in advance.

Imagine one project where people want to use estimates of "easy" or "hard".  And another shop wants to use estimates like "1 day", "2 days", "3 days", "4 or more days".

Each shop would use 

$ pitz-add-estimate

to make the estimates they want.  Then, when they make a task, they choose the estimate from the pre-defined list.

pitz already has a few of these estimate schemes built-in already.  Type this to see them:

$ pitz-add-estimate --from-builtin-estimates

And you'll see them.  It is easy to add new ones just for your project.  But if you come up with a useful estimate scheme, I'd be happy to add it to pitz itself, so other people can choose it.

**Comment by mw44118** [comment]
Any thoughts on this?  I might close this issue.
