### ISSUE TITLE
Install requires docutils

### ISSUE THREAD

**Issue by nstinus** [mw44118/pitz#9]
pull nstinus/pitz/master, trivial fix enclosed.

**Comment by mw44118** [comment]
Whoops!  Is docutils not lizted?

**Comment by nstinus** [comment]
Nope. Trivial to fix though.

**Comment by mw44118** [comment]
Thanks for the info! I just pushed a new setup.py.

matt

On Sat, Aug 25, 2012 at 6:10 PM, Nicolas Stinus notifications@github.comwrote:

> Nope. Trivial to fix though.
> 
> Le 25 août 2012 à 17:58, "W. Matthew Wilson" notifications@github.com a
> écrit :
> 
> > Whoops! Is docutils not lizted?
> > On Aug 25, 2012 3:24 PM, "Nicolas Stinus" notifications@github.com
> > wrote:
> > 
> > > —
> > > Reply to this email directly or view it on GitHub.
> > > —
> > > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mw44118/pitz/issues/9#issuecomment-8028001.

## 

W. Matthew Wilson
matt@tplus1.com
http://tplus1.com
